### ISSUE TITLE
S60v3 support

### ISSUE THREAD

**Issue by ghost** [baranovskiykonstantin/rfterm#1]
> Symbian S60v5 application to exchange data over Bluetooth using RFCOMM protocol.

Would it works on Symbian S60v3 (Nokia N82/N95, etc)?

**Comment by baranovskiykonstantin** [comment]
I'm not sure it would but if you accept to test this app on your devices I will install SDK and prepare package for S60v3.

Nevertheless you can try to install existing *.sis package (it may warn that device not supported but will allow to install).
The keyboard support is present and touch API has backward compatibility.

**Comment by ghost** [comment]
> Nevertheless you can try to install existing *.sis package

OK, I will try to install existed `*.sis` firstly.

**Comment by baranovskiykonstantin** [comment]
I've prepared the package for S60v3. Could you test it please? Any suggestions or complaints are welcome.
[RFterm_S60v3.zip](https://github.com/baranovskiykonstantin/rfterm/files/6210454/RFterm_S60v3.zip)

**Comment by baranovskiykonstantin** [comment]
@Symbian9, could you confirm the S60v3 support?

**Comment by NuruDashdamir** [comment]
> I've prepared the package for S60v3. Could you test it please? Any suggestions or complaints are welcome.
> [RFterm_S60v3.zip](https://github.com/baranovskiykonstantin/rfterm/files/6210454/RFterm_S60v3.zip)
> 

I used it for a while on Nokia E5-00, didn't encounter any bugs or issues :)

**Comment by ghost** [comment]
Closing as resolved.
